# These are supported funding model platforms

custom: https://img-blog.csdnimg.cn/20210328212224845.jpg?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3Fpeml4aTgz,size_16,color_FFFFFF,t_70
